### ISSUE TITLE
Problems with colons in name for author/source

### ISSUE THREAD

**Issue by Someone0nEarth** [cooklang/cooklang-rs#11]
Hello,

when a colon is in the name part, it will led to unexpected [results](https://github.com/Someone0nEarth/cooklang-rs/blob/1371f22ae14bbceeeb8b957b8ed7ca28199a8c4b/src/metadata.rs#L561):

![image](https://github.com/cooklang/cooklang-rs/assets/99350163/ab37818c-6bf5-4d3d-b4fc-9535eb774e11)

It looks like, that current [validation](rs/blob/b0f7e3460ec702bf624592b4ddcc487562a5f7be/src/metadata.rs#L440) of an URL is not considering this case:

`if let Ok(url) = Url::parse(s) {`

If this validation will be improved, the `:` can be added to the regex for name and url ([see](https://github.com/cooklang/cooklang-rs/pull/10)) .

Have fun,
   someone.earth

**Comment by Zheoni** [comment]
I see why this is a problem. However I don't know if extending the allowed set of characters is the right solution.

Maybe it's better for the name to be whatever is before the `<url>` part. And also if it's empty or only whitespace it should be `None`, not an empty or whitespace string.

So:
- `Rachel: Best recipes <https://rachel.url>` -> `Rachel: Best recipes` | `https://rachel.url`
- `     <https://rachel.url>` -> None | `https://rachel.url`

I think this is a better solution because it's simpler and behaves as expected no matter what the user writes.

**Comment by Someone0nEarth** [comment]
With the current implementation, there are two issues dealiung with ":" in names:

Issue 1: Names first word are tailored with ":" will be interpreted as an URL ([test](https://github.com/Someone0nEarth/cooklang-rs/blob/1371f22ae14bbceeeb8b957b8ed7ca28199a8c4b/src/metadata.rs#L561)):

- `Rachel: Best recipes <https://rachel.url>` -> no name and url `rachel: Best recipes <https://rachel.url>`

- `Rachel: Best recipes` -> no name and url `rachel: Best recipes`

Issue 2: Names containing ":" after the first word, everything will be interpreted as name ([test](https://github.com/Someone0nEarth/cooklang-rs/blob/1371f22ae14bbceeeb8b957b8ed7ca28199a8c4b/src/metadata.rs#L565)):

- `Rachel Peterson: Best recipes <https://rachel.url>` -> name `Rachel Peterson: Best recipes <https://rachel.url>` and no URL

This happens because of the [current](https://github.com/cooklang/cooklang-rs/issues/rs/blob/b0f7e3460ec702bf624592b4ddcc487562a5f7be/src/metadata.rs#L440) implementation of URL detection code: `if let Ok(url) = Url::parse(s) {` .

My [PR](https://github.com/cooklang/cooklang-rs/pull/10) is not adressing  the issues with  ":" (the PR is only improving the current behavior, if the names containg several special chars).

For a better differentiating, I will raise more issues for the other names and url issues.

I am with you, that a more general solution would fix this issue and also adresses the thingy of my PR. But this would maybe break the current behavior of the name-url dualism (it can be a name OR an URL) and won't be very backwards combatible.

I would suggets one of the following two approaches:

1. A better URL detection, for dealing with the name-url dualism (and than for example using my PR for improved special char support in the name part): Higher backwards combability, but less clean  
2. The URL part has always to be encapsulated with `<..>`, even when there is no given name and the part before <url> will be completly interpreted as the name: Less backwards combaility, but cleaner

I personally would prefer 2. .

What do you think?

**Comment by Zheoni** [comment]
I don't know. For this I don't care too much about backwards compatibility because it's not a core language feature and the crate is not in a stable version.

I like 2 for the same reason: it's cleaner and no room for error. But there's something about just writting the URL that I like a lot.

```cooklang
>> source: https://www.youtube.com/watch?v=1tZcGfRouIE
```

The problem is that `rachel: best recipes` is actually a well formed URL where `rachel` is the protocol.

Another solution can be:
- Anything until `<..>` is the name and then the URL.
- If the string starts with `http` or `https` then test if it's a valid URL. So only http(s) URLs can be bare, without the `<..>`

This would preserve backwards compatibility with 99% of uses and allow any characters as the name. What do you think?

**Comment by Someone0nEarth** [comment]
> I don't know. For this I don't care too much about backwards compatibility because it's not a core language feature and the crate is not in a stable version.

Aye


> I like 2 for the same reason: it's cleaner and no room for error. But there's something about just writting the URL that I like a lot.
> 
> ```
> >> source: https://www.youtube.com/watch?v=1tZcGfRouIE
> ```

I see, and yep, its very convenient :) 

> The problem is that `rachel: best recipes` is actually a well formed URL where `rachel` is the protocol.

True, but yesterday when using the debugger on the url-parsing, I saw, that for this the "host" would be None. This could be used as a second critera (next to Ok(url)), if this is a valid URL. Already tried it and it worked for these kind of examples.

> * Anything until `<..>` is the name and then the URL.
👍 (except <...> is an invalid url, see approach at the bottom)

> * If the string starts with `http` or `https` then test if it's a valid URL. So only http(s) URLs can be bare, without the `<..>`

I would like to keep a general approach for the protocol: For example it would be nice, that smb://, sftp:// etc. will worked, too. I think, this can be achieved with the improved "is valid url" check, I just mentioned (host != None). This will work for the very most cases. And if there would be a very rare special case, I would bet, the check can be also improved to handle that.

So, our final approach would look like this?

- `name <valid url>` -> as `name` & `url`
- `name <invalid url>` -> as `name`
- `name` -> as `name`
- `invalid url` -> as `name`
- `<invalid url>` -> as `name`
- `valid url` -> as `url`
- `<valid url>` -> as `url`

What do you think?

**Comment by Zheoni** [comment]
Very good to have noticed that the host is `None`! I think it will be fine if we check on that. So yes, that approach looks good to me.

**Comment by Someone0nEarth** [comment]
I will finish the implementation later ✌️
